#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ihatemoney"
name = "I Hate Money"
description.en = "Simple app to manage your collective expenses"
description.fr = "Gérez simplement vos dépenses collectives"

version = "6.1.3~ynh2"

maintainers = ["Jocelyn Delalande"]

[upstream]
license = "MIT"
website = "http://ihatemoney.org/"
demo = "https://ihatemoney.org/demo/"
admindoc = "https://ihatemoney.readthedocs.org/"
code = "https://github.com/spiral-project/ihatemoney"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "300M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ihatemoney"

    [install.init_main_permission]
    help.en = "Each ihatemoney project is protected by a password anyways"
    help.fr = "Les projets ihatemoney sont protégés par un mot de passe dans tous les cas"
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://github.com/spiral-project/ihatemoney/archive/refs/tags/6.1.3.tar.gz"
    sha256 = "5f47a1c4ba18684ce1c645869202d36cfea94f4dc3b974d694a6dcef292c38e9"
    prefetch = false

    # Only here as a notification source, need to change version in _common.sh
    autoupdate.strategy = "latest_github_release"
    autoupdate.needs_manual_tweaks = true

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.auth_header = true
    
    [resources.apt]
    packages = "mariadb-server, python3-dev, python3-venv, libffi-dev, libssl-dev"

    [resources.database]
    type = "mysql"
