packaging_format = 2

id = "ihatemoney"
name = "I Hate Money"
description.en = "Simple app to manage your collective expenses"
description.fr = "Gérez simplement vos dépenses collectives"

version = "5.2.0~ynh2"

maintainers = ["Jocelyn Delalande"]

[upstream]
license = "MIT"
website = "http://ihatemoney.org/"
admindoc = "https://ihatemoney.readthedocs.org/"
code = "https://github.com/spiral-project/ihatemoney"
demo = "https://ihatemoney.org/demo/"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.0.9"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "?" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "?" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "?" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ihatemoney"

    [install.init_main_permission]
    help.en = "Each ihatemoney project is protected by a password anyways"
    help.fr = "Les projets ihatemoney sont protégés par un mot de passe dans tous les cas"
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, python3-dev, python3-venv, libffi-dev, libssl-dev"

    [resources.database]
    type = "mysql"
