#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# SPECIFIC SETUP
#=================================================
ynh_script_progression "Building venv..."

__ynh_python_venv_setup --venv_dir="$install_dir/venv" --packages "${pip_dependencies[*]}"
python_venv_site_packages=$(__ynh_python_venv_get_site_packages_dir -d "$install_dir/venv")

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

# Secret key for cookies encryption.
secret_key=$(ynh_string_random --length=32)
ynh_app_setting_set --key=secret_key --value="$secret_key"

hashed_password=$(_hash_password "$password")
ynh_app_setting_set --key=hashed_password --value="$hashed_password"

# Allows to comment some config lines if not using sub path
sub_path_only="$(if [[ "$path" == "/" ]]; then echo '# ' ; else echo ''; fi)"

ynh_config_add --template="gunicorn.conf.py" --destination="$install_dir/gunicorn.conf.py"
ynh_config_add --template="ihatemoney.cfg" --destination="$install_dir/ihatemoney.cfg"

chown -R "$app:www-data" "$install_dir"
# Configure log directory
mkdir -p "/var/log/$app"
chown -R "$app:$app" "/var/log/$app"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."


ynh_config_add_systemd

yunohost service add "$app" --description="$app daemon for IHateMoney" --log=systemd

ynh_systemctl --service="$app" --action="start" --wait_until="Listening at"

wait_gunicorn_start

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
