#!/bin/bash
set -u

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# supervisord and other Debian dependencies remain installed
# there is no way to know if they are used by other programs

# Retrieve arguments
app=ihatemoney
domain=$(ynh_app_setting_get $app domain)
db_user=$app
db_name=$app
root_pwd=$(sudo cat /etc/yunohost/mysql)

# Drop database
ynh_mysql_drop_db $db_name
ynh_mysql_drop_user $db_user

# Remove src
sudo rm -rf /opt/yunohost/ihatemoney/

# Remove settings
sudo rm -rf /etc/ihatemoney
sudo rm /etc/supervisor/conf.d/ihatemoney.conf
sudo rm /etc/nginx/conf.d/$domain.d/ihatemoney.conf

# Restart services
sudo supervisorctl stop budget
sudo service supervisor force-reload
sudo service nginx reload

# Delete user
sudo userdel ihatemoney
