#!/bin/bash

# Source app helpers
source /usr/share/yunohost/helpers

# Get multi-instances specific variables
app=$YNH_APP_INSTANCE_NAME

# Set app specific variables
dbname=$app
dbuser=$app

# Retrieve old app settings
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)
dbpass=$(ynh_app_setting_get "$app" mysqlpwd)


# Source local utils
if [ ! -e _common.sh ]; then
	# Fetch the local helpers files, because unavail to restore script
	sudo cp ../settings/scripts/_common.sh ./_common.sh
	sudo chmod a+rx _common.sh
fi

source _common.sh

ynh_abort_if_errors

test -d $INSTALL_DIR && ynh_die \
"The destination directory '$INSTALL_DIR' already exists.\
 You should safely delete it before restoring this app."

test -f $nginx_conf_path && ynh_die \
"The NGINX configuration already exists at '${nginx_conf_path}'.
 You should safely delete it before restoring this app."

test -f $supervisor_conf_path && ynh_die \
"The Supervisor configuration already exists at '${supervisor_conf_path}'.
 You should safely delete it before restoring this app."

test -f $gunicorn_conf_path && ynh_die \
"The Gunicorn configuration already exists at '${gunicorn_conf_path}'.
 You should safely delete it before restoring this app."

install_apt_dependencies

create_unix_user

create_system_dirs

# Restore all backed-up files
ynh_restore

# Create and restore the database
ynh_mysql_create_db "$dbname" "$dbuser" "$dbpass"
ynh_mysql_connect_as "$dbuser" "$dbpass" "$dbname" < ./db.sql

# Reload
sudo systemctl reload nginx
sudo systemctl restart supervisor
sudo supervisorctl restart budget
